# Generated by Django 4.2.3 on 2023-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "active_ingredient",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "presentation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "original_price",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PVF C/IGV"
                    ),
                ),
                (
                    "tops_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tops unidades"
                    ),
                ),
                (
                    "tops_discount_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tops descuento unidades"
                    ),
                ),
                (
                    "tops_scale1_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tops Escala 1 unidades"
                    ),
                ),
                (
                    "tops_scale1_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Tops Escala 1 descuento porcentaje",
                    ),
                ),
                (
                    "tops_scale2_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tops Escala 2 unidades"
                    ),
                ),
                (
                    "tops_scale2_discount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tops Escala 2 descuento porcentaje",
                    ),
                ),
                (
                    "farma_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Farma unidades"
                    ),
                ),
                (
                    "farma_discount_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Farma descuento unidades"
                    ),
                ),
                (
                    "farma_scale1_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Farma Escala 1 unidades"
                    ),
                ),
                (
                    "farma_scale1_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Farma Escala 1 descuento porcentaje",
                    ),
                ),
                (
                    "farma_scale2_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Farma Escala 2 unidades"
                    ),
                ),
                (
                    "farma_scale2_discount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Farma Escala 2 descuento porcentaje",
                    ),
                ),
                (
                    "mayoristas_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mayoristas unidades"
                    ),
                ),
                (
                    "mayoristas_discount_units",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Mayoristas descuento unidades",
                    ),
                ),
                (
                    "mayoristas_scale1_units",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Mayoristas Escala 1 unidades",
                    ),
                ),
                (
                    "mayoristas_scale1_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Mayoristas Escala 1 descuento porcentaje",
                    ),
                ),
                (
                    "mayoristas_scale2_units",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Mayoristas Escala 2 unidades",
                    ),
                ),
                (
                    "mayoristas_scale2_discount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Mayoristas Escala 2 descuento porcentaje",
                    ),
                ),
                (
                    "institutions_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Instituciones unidades"
                    ),
                ),
                (
                    "institutions_discount_units",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Instituciones descuento unidades",
                    ),
                ),
                (
                    "institutions_scale1_units",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Instituciones Escala 1 unidades",
                    ),
                ),
                (
                    "institutions_scale1_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Instituciones Escala 1 descuento porcentaje",
                    ),
                ),
                (
                    "institutions_scale2_units",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Instituciones Escala 2 unidades",
                    ),
                ),
                (
                    "institutions_scale2_discount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Instituciones Escala 2 descuento porcentaje",
                    ),
                ),
            ],
        ),
    ]
