# Generated by Django 4.2.3 on 2023-09-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_quoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="client",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
