# Generated by Django 4.2.3 on 2023-09-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_quoteitem_client"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="farma_scale1_discount",),
        migrations.RemoveField(model_name="product", name="farma_scale2_discount",),
        migrations.RemoveField(
            model_name="product", name="institutions_discount_units",
        ),
        migrations.RemoveField(
            model_name="product", name="institutions_scale1_discount",
        ),
        migrations.RemoveField(
            model_name="product", name="institutions_scale2_discount",
        ),
        migrations.RemoveField(
            model_name="product", name="mayoristas_scale1_discount",
        ),
        migrations.RemoveField(
            model_name="product", name="mayoristas_scale2_discount",
        ),
        migrations.RemoveField(model_name="product", name="tops_scale1_discount",),
        migrations.RemoveField(model_name="product", name="tops_scale2_discount",),
        migrations.AddField(
            model_name="product",
            name="farma_scale1_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Farma Escala 1 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="farma_scale2_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Farma Escala 2 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="farma_scale3_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Farma Escala 3 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="farma_scale3_units",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Farma Escala 3 unidades"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="institutions_scale1_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Instituciones Escala 1 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="institutions_scale2_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Instituciones Escala 2 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="institutions_scale3_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Instituciones Escala 3 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="institutions_scale3_units",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Instituciones Escala 3 unidades"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mayoristas_scale1_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Mayoristas Escala 1 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mayoristas_scale2_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Mayoristas Escala 2 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mayoristas_scale3_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Mayoristas Escala 3 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mayoristas_scale3_units",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Mayoristas Escala 3 unidades"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tops_scale1_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Tops Escala 1 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tops_scale2_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Tops Escala 2 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tops_scale3_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Tops Escala 3 precio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tops_scale3_units",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Tops Escala 3 unidades"
            ),
        ),
    ]
