# Generated by Django 4.2.3 on 2023-09-05 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_remove_product_farma_scale1_discount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name": "Producto"},
        ),
        migrations.AlterModelOptions(
            name="quoteitem",
            options={
                "verbose_name": "Item de cotización",
                "verbose_name_plural": "Items de cotización",
            },
        ),
        migrations.RemoveField(model_name="quoteitem", name="client",),
        migrations.RemoveField(model_name="quoteitem", name="user",),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("client", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
            },
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.quote",
            ),
        ),
    ]
