# Generated by Django 4.2.3 on 2023-09-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_product_options_alter_quoteitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
