# Generated by Django 4.2.3 on 2023-09-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="bonus_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="quoteitem", unique_together={("quote", "product")},
        ),
    ]
