# Generated by Django 4.2.3 on 2023-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_quoteitem_bonus_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="Generico", max_length=50),
            preserve_default=False,
        ),
    ]
