# Generated by Django 4.2.3 on 2023-09-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="farma_discount_units",),
        migrations.RemoveField(model_name="product", name="farma_scale1_price",),
        migrations.RemoveField(model_name="product", name="farma_scale1_units",),
        migrations.RemoveField(model_name="product", name="farma_scale2_price",),
        migrations.RemoveField(model_name="product", name="farma_scale2_units",),
        migrations.RemoveField(model_name="product", name="farma_scale3_price",),
        migrations.RemoveField(model_name="product", name="farma_scale3_units",),
        migrations.RemoveField(model_name="product", name="farma_units",),
        migrations.RemoveField(model_name="product", name="institutions_scale1_price",),
        migrations.RemoveField(model_name="product", name="institutions_scale1_units",),
        migrations.RemoveField(model_name="product", name="institutions_scale2_price",),
        migrations.RemoveField(model_name="product", name="institutions_scale2_units",),
        migrations.RemoveField(model_name="product", name="institutions_scale3_price",),
        migrations.RemoveField(model_name="product", name="institutions_scale3_units",),
        migrations.RemoveField(model_name="product", name="institutions_units",),
        migrations.RemoveField(model_name="product", name="mayoristas_discount_units",),
        migrations.RemoveField(model_name="product", name="mayoristas_scale1_price",),
        migrations.RemoveField(model_name="product", name="mayoristas_scale1_units",),
        migrations.RemoveField(model_name="product", name="mayoristas_scale2_price",),
        migrations.RemoveField(model_name="product", name="mayoristas_scale2_units",),
        migrations.RemoveField(model_name="product", name="mayoristas_scale3_price",),
        migrations.RemoveField(model_name="product", name="mayoristas_scale3_units",),
        migrations.RemoveField(model_name="product", name="mayoristas_units",),
        migrations.RemoveField(model_name="product", name="original_price",),
        migrations.RemoveField(model_name="product", name="price",),
        migrations.RemoveField(model_name="product", name="tops_discount_units",),
        migrations.RemoveField(model_name="product", name="tops_scale1_price",),
        migrations.RemoveField(model_name="product", name="tops_scale1_units",),
        migrations.RemoveField(model_name="product", name="tops_scale2_price",),
        migrations.RemoveField(model_name="product", name="tops_scale2_units",),
        migrations.RemoveField(model_name="product", name="tops_scale3_price",),
        migrations.RemoveField(model_name="product", name="tops_scale3_units",),
        migrations.RemoveField(model_name="product", name="tops_units",),
        migrations.RemoveField(model_name="quoteitem", name="bonus_quantity",),
        migrations.RemoveField(model_name="quoteitem", name="quantity_2",),
        migrations.RemoveField(model_name="quoteitem", name="unit_price_2",),
        migrations.AddField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio original unitario S/IGV",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price_farma",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio Farma S/IGV",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price_institutions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio Instituciones S/IGV",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price_mayoristas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio Mayoristas S/IGV",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price_tops",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio Tops S/IGV",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="PVF S/IGV"
            ),
        ),
    ]
