# Generated by Django 4.2.3 on 2024-12-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_remove_product_farma_discount_units_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "ruc",
                    models.CharField(max_length=11, unique=True, verbose_name="RUC"),
                ),
            ],
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes",},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150, verbose_name="Dirección")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitud"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitud"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={"verbose_name": "Local", "verbose_name_plural": "Locales",},
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_at", models.DateTimeField(auto_now_add=True)),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Visita", "verbose_name_plural": "Visitas",},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterField(
            model_name="product",
            name="active_ingredient",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Componente activo"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50, verbose_name="Categoría"),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="presentation",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Presentaciòn"
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.quote",
                verbose_name="Cotización",
            ),
        ),
        migrations.CreateModel(
            name="VisitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.visit"
                    ),
                ),
            ],
        ),
    ]
