# Generated by Django 4.2.3 on 2024-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_client_location_visit_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit", name="check_in_at", field=models.DateTimeField(),
        ),
    ]
