# Generated by Django 4.2.3 on 2024-12-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_visit_check_in_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='quote',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteItem',
        ),
    ]
