# Generated by Django 4.2.3 on 2024-12-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_quoteitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=10, max_digits=13, verbose_name="Latitud"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=10, max_digits=13, verbose_name="Longitud"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name="visit",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
