# Generated by Django 4.2.3 on 2024-12-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_location_latitude_alter_location_longitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visititem",
            options={
                "verbose_name": "Item de visita",
                "verbose_name_plural": "Items de visita",
            },
        ),
        migrations.AlterUniqueTogether(
            name="visititem", unique_together={("visit", "product")},
        ),
    ]
