# Generated by Django 4.2.3 on 2024-12-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_visititem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="active_ingredient",),
        migrations.RemoveField(model_name="product", name="presentation",),
        migrations.RemoveField(model_name="product", name="unit_price",),
        migrations.RemoveField(model_name="product", name="unit_price_farma",),
        migrations.RemoveField(model_name="product", name="unit_price_institutions",),
        migrations.RemoveField(model_name="product", name="unit_price_mayoristas",),
        migrations.RemoveField(model_name="product", name="unit_price_tops",),
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="visititem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="visititem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
