# Generated by Django 4.2.3 on 2024-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_product_active_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="googlemaps_place_id",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="ID de lugar de Google Maps",
            ),
        ),
    ]
