# Generated by Django 4.2.3 on 2025-01-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_location_googlemaps_place_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="main.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=12, max_digits=15, verbose_name="Latitud"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=12, max_digits=15, verbose_name="Longitud"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="latitude",
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name="visit",
            name="longitude",
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
