# Generated by Django 4.2.3 on 2025-01-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_location_client_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Línea RX", "Linea Rx"),
                    ("Línea OTC", "Linea Otc"),
                    ("Línea GX", "Linea Gx"),
                    ("Personal Care", "Personal Care"),
                ],
                max_length=50,
                verbose_name="Categoría",
            ),
        ),
    ]
