# Generated by Django 4.2.3 on 2025-01-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_visititem_visit_superviseduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visititem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
    ]
