# Generated by Django 4.2.3 on 2025-01-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_visititem_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuidor",
                "verbose_name_plural": "Distribuidores",
            },
        ),
        migrations.AlterUniqueTogether(name="visititem", unique_together=set(),),
        migrations.AddField(
            model_name="visititem",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.distributor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visititem", unique_together={("visit", "product", "distributor")},
        ),
    ]
