# Generated by Django 4.2.3 on 2025-01-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_distributor_alter_visititem_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("quantity_a", models.IntegerField(blank=True, null=True)),
                (
                    "commission_a",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("quantity_b", models.IntegerField(blank=True, null=True)),
                (
                    "commission_b",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de producto",
                "verbose_name_plural": "Precios de productos",
                "unique_together": {("valid_from", "valid_to", "product")},
            },
        ),
    ]
