# Generated by Django 4.2.3 on 2025-01-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_rename_check_in_at_visit_check_in_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="attendance", unique_together=set(),),
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(model_name="attendance", name="date",),
    ]
