# Generated by Django 4.2.3 on 2025-01-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_attendance_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="latitude_check_in",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=15,
                null=True,
                verbose_name="Latitud Check In",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="latitude_check_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=15,
                null=True,
                verbose_name="Latitud Check Out",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude_check_in",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=15,
                null=True,
                verbose_name="Longitud Check In",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude_check_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=15,
                null=True,
                verbose_name="Longitud Check Out",
            ),
        ),
    ]
