# Generated by Django 4.2.3 on 2025-01-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_attendance_latitude_check_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productprice", name="price",),
        migrations.AddField(
            model_name="productprice",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visititem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
    ]
