# Generated by Django 4.2.3 on 2025-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_productprice_price_productprice_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="check_in", field=models.DateTimeField(),
        ),
    ]
