# Generated by Django 4.2.3 on 2025-01-16 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_alter_attendance_check_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Principio activo'),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='superviseduser',
            name='supervised_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
