# Generated by Django 4.2.3 on 2025-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_client_ruc_alter_visit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RUC'),
        ),
    ]
