# Generated by Django 4.2.3 on 2025-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_client_name_alter_client_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
