# Generated by Django 4.2.3 on 2025-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Dirección'),
        ),
    ]
