# Generated by Django 4.2.3 on 2025-02-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
