# Generated by Django 4.2.3 on 2025-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_scheduledvisit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['user', 'check_in', 'location'], name='main_visit_user_id_42848b_idx'),
        ),
    ]
