# Generated by Django 4.2.3 on 2025-02-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_visit_main_visit_user_id_42848b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='latitude_check_in',
            field=models.DecimalField(decimal_places=12, default=-12.125185143921335, max_digits=15, verbose_name='Latitud Check In'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude_check_in',
            field=models.DecimalField(decimal_places=12, default=-77.02505759860534, max_digits=15, verbose_name='Longitud Check In'),
            preserve_default=False,
        ),
    ]
