# Generated by Django 4.2.3 on 2025-02-24 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_attendance_check_in_photo_attendance_check_out_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
